spring.application.name=ticket-router

#openai configuration
openai.api-key=${LLM_API_KEY}
openai.base-url=https://api.openai.com/v1
openai.model=gpt-4o-mini

#will allow 3 retries with 1 second wait duration between each retry
resilience4j.retry.instances.openai.max-attempts=3
resilience4j.retry.instances.openai.wait-duration=1s

#circuit breaker configuration
#if 50% of the last 10 calls fail, the circuit breaker will open for 10 seconds
resilience4j.circuitbreaker.instances.openai.sliding-window-size=10
resilience4j.circuitbreaker.instances.openai.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.openai.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.openai.wait-duration-in-open-state=10s