CREATE TABLE user_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assigned_team VARCHAR(255),
    category VARCHAR(255),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    message VARCHAR(5000) NOT NULL,
    priority VARCHAR(255),
    reasoning VARCHAR(1000),
    user_profile_id BIGINT NOT NULL,

    CONSTRAINT ticket_priority_check
        CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),

    CONSTRAINT fk_ticket_user_profile
        FOREIGN KEY (user_profile_id)
        REFERENCES user_profile(id)
);