-- Introduces a proper RBAC schema (user_type / permission / mapping table)
-- to replace the fixed users.role enum, and adds a ticket status workflow
-- for department staff.

-- ---------- Catalog tables ----------

CREATE TABLE user_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    department_team_name VARCHAR(100)
);

CREATE TABLE permission (
    permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_name VARCHAR(100) NOT NULL UNIQUE,
    permission_description VARCHAR(255)
);

-- Many-to-many mapping: which permissions each user type has.
CREATE TABLE user_type_permissions (
    user_type_id BIGINT NOT NULL REFERENCES user_type (id),
    permission_id BIGINT NOT NULL REFERENCES permission (permission_id),
    PRIMARY KEY (user_type_id, permission_id)
);


-- ---------- Seed user types ----------
-- department_team_name matches the exact "assignedTeam" values the AI
-- router already produces (see TicketRoutingPrompt), so department ticket
-- filtering is a simple equality check.

INSERT INTO user_type (name, description, department_team_name) VALUES
    ('ADMIN', 'System administrator', NULL),
    ('CUSTOMER', 'Ticket-submitting end user', NULL),
    ('ACCOUNTS_STAFF', 'Accounts Department staff', 'Accounts Department'),
    ('ENGINEERING_STAFF', 'Engineering Department staff', 'Engineering Department'),
    ('IAM_STAFF', 'IAM Team staff', 'IAM Team'),
    ('PRODUCT_STAFF', 'Product Development Team staff', 'Product Development Team'),
    ('SUPPORT_STAFF', 'Customer Service Team staff', 'Customer Service Team');


-- ---------- Seed permissions ----------

INSERT INTO permission (permission_name, permission_description) VALUES
    ('SUBMIT_TICKET', 'Submit a new support ticket'),
    ('VIEW_OWN_TICKETS', 'View tickets the user personally submitted'),
    ('VIEW_ALL_TICKETS', 'View every ticket across all departments'),
    ('VIEW_DEPARTMENT_TICKETS', 'View tickets assigned to the user''s own department'),
    ('UPDATE_TICKET_STATUS', 'Change a ticket''s status (accepted/rejected/in progress/completed)'),
    ('DELETE_REJECTED_TICKET', 'Delete a ticket that has been marked rejected'),
    ('DELETE_LOW_PRIORITY_TICKET', 'Delete a LOW priority ticket'),
    ('MANAGE_USERS', 'Create new staff/department user accounts and assign roles');


-- ---------- Map permissions to user types ----------

INSERT INTO user_type_permissions (user_type_id, permission_id)
SELECT ut.id, p.permission_id
FROM user_type ut, permission p
WHERE ut.name = 'ADMIN'
  AND p.permission_name IN ('VIEW_ALL_TICKETS', 'MANAGE_USERS', 'DELETE_LOW_PRIORITY_TICKET');

INSERT INTO user_type_permissions (user_type_id, permission_id)
SELECT ut.id, p.permission_id
FROM user_type ut, permission p
WHERE ut.name = 'CUSTOMER'
  AND p.permission_name IN ('SUBMIT_TICKET', 'VIEW_OWN_TICKETS');

INSERT INTO user_type_permissions (user_type_id, permission_id)
SELECT ut.id, p.permission_id
FROM user_type ut, permission p
WHERE ut.name IN ('ACCOUNTS_STAFF', 'ENGINEERING_STAFF', 'IAM_STAFF', 'PRODUCT_STAFF', 'SUPPORT_STAFF')
  AND p.permission_name IN ('VIEW_DEPARTMENT_TICKETS', 'UPDATE_TICKET_STATUS', 'DELETE_REJECTED_TICKET');


-- ---------- Migrate users.role -> users.user_type_id ----------
-- Existing ADMIN/USER accounts map 1:1 to the new ADMIN/CUSTOMER types.
-- Existing AGENT accounts are folded into SUPPORT_STAFF (Customer Service
-- Team) as the closest equivalent of a generic "staff" role.

ALTER TABLE users ADD COLUMN user_type_id BIGINT;

UPDATE users u
SET user_type_id = ut.id
FROM user_type ut
WHERE (u.role = 'ADMIN' AND ut.name = 'ADMIN')
   OR (u.role = 'USER'  AND ut.name = 'CUSTOMER')
   OR (u.role = 'AGENT' AND ut.name = 'SUPPORT_STAFF');

ALTER TABLE users ALTER COLUMN user_type_id SET NOT NULL;

ALTER TABLE users
    ADD CONSTRAINT fk_users_user_type
    FOREIGN KEY (user_type_id)
    REFERENCES user_type (id);

ALTER TABLE users DROP COLUMN role;


-- ---------- Ticket status workflow ----------

ALTER TABLE ticket ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'PENDING';

ALTER TABLE ticket
    ADD CONSTRAINT ticket_status_check
    CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED'));
